### ISSUE TITLE
Solution to persistence problems

### ISSUE THREAD

**Issue by tddawson** [tcbarrus/zeus#12]
It would be best if we had a way to save the updated json file from the user's nutrition table so that it can be used by other areas of the site. It would also be best for the notes section.
- Look into this: http://www.w3schools.com/html/html5_webstorage.asp as a possible solution.

If all else fails, we'll just create a few different states of json files that can be used to demonstrate the functionality.

**Comment by nmspackman** [comment]
https://thiscouldbebetter.wordpress.com/2012/12/18/loading-editing-and-saving-a-text-file-in-html5-using-javascrip/

**Comment by chloehale** [comment]
We'll probably put it in local storage.  See the Resources Wiki page.
